### PR TITLE
Update links in DESCRIPTION

### PR DESCRIPTION
**Pull request by olivroy**
Considerchanging link in the About section of the gh repo! It contains these outdated links as well

### CODE REVIEW

**Comment by amymariemason** [comment]
Thank you for letting me know! You can tell it's the first time I've tried using this workstream to get a website working :)

**Comment by olivroy** [comment]
No problem! Well, it seems your setup is fine. However, there seems to be some failing snapshot tests that you will have to check locally (unrelated to this PR).

About the link I am just suggesting to change
Capture d’écran, le 2024-01-10 à 8 20 44 a m

with https://amymariemason.github.io/MR/ instead.

Let me know if you have other questions, happy to help

**Comment by amymariemason** [comment]
Yeah, the failing snapshot is odd. I can't get it to reproduce on my machine, so re-installing all packages to try to work out what is causing that error - it was fine at the end of the last year, so my assumption is some package update that now throws a warning where it didn't before.

**Comment by olivroy** [comment]
Thanks for the update. Now that I see better the diff, this is just due to testthat 3.2.0 changing the way it displays snapshots !
Cheers

**Pull request merged**
